version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    groups:
      npm-production-dependencies:
        dependency-type: production
        patterns:
          - "*"
        exclude-patterns:
          - "@iqb/responses"
      npm-development-dependencies:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
